apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: jfrog-oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
            - containerPort: 8081
            - containerPort: 8082
          volumeMounts:
            - name: data
              mountPath: /var/opt/jfrog/artifactory
          env:
            - name: JF_ROUTER_ENTRYPOINTS_EXTERNALPORT
              value: "8082"
      volumes:
        - name: data
          emptyDir: {}
