apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
  namespace: jfrog-oss
spec:
  selector:
    app: artifactory
  ports:
    - name: "artifactory"
      protocol: TCP
      port: 8081
      targetPort: 8081

    - name: "artifactory-ui"
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort # Use NodePort para acessar de fora do cluster, ou ClusterIP para acessar internamente.
